baseURL: /
languageCode: en-us
defaultContentLanguage: en
title: PSWA
theme: cayman-hugo-theme


# Syntax highlighting
pygmentsCodefences: true
pygmentsStyle: pygments

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

params:
  # Header text, can be markdown
  project_name: Protected Static Web Apps
  project_tagline: pswa is a simple web content/proxy server that embodies enterprise zero trust security

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2006-01-02

  # Footer text, can be markdown
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme).

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex: true

  # Breakpoints
  large_breakpoint: 64em
  medium_breakpoint: 42em

  # Header colors
  header_heading_color: "#fff"
  header_background_color: "#159957"
  header_background_color_secondary: "#155799"

  # Text colors
  section_headings_color: "#159957"
  body_text_color: "#606c71"
  body_link_color: "#1e6bb8"
  blockquote_text_color: "#819198"

  # Code colors
  code_background_color: "#f3f6fa"
  code_text_color: "#567482"

  # Border colors
  border_color: "#dce6f0"
  table_border_color: "#e9ebec"
  hr_border_color: "#eff0f1"

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Admin
      url: /admin/
      weight: 2
    - name: Internal
      url: /internal/
      weight: 3
    - name: Login
      url: /.auth/login/aad
      weight: 4
    - name: Logout
      url: /.auth/logout
      weight: 5
    - name: Me
      url: /.auth/me
      weight: 6