version: "3"
services:
  pswa:
    image: ghcr.io/yaegashi/pswa
    build: .
    env_file:
      - pswa.env
    volumes:
      - ./pswa.config.json:/home/site/wwwroot/pswa.config.json
    ports:
      - "8080:8080"
